cask_args appdir: '/Applications'

# Third-party taps
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/dupes'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/php'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'thoughtbot/formulae'

# Core Utilities
brew 'bash'
brew 'coreutils'
brew 'findutils'
brew 'homebrew/dupes/grep'
brew 'imagemagick'

# Libraries
brew 'libyaml'
brew 'openssl'
brew 'qt'

# Services
brew 'postgresql'
brew 'redis'

# Tools
brew 'fasd'
brew 'git'
brew 'heroku-toolbelt'
brew 'hub'
brew 'macvim', args: ['with-cscope', 'with-lua', 'with-override-system-vim']
brew 'pick'
brew 'rcm'
brew 'the_silver_searcher'
brew 'trash'

# PHP
brew 'php71'

# Ruby
brew 'rbenv'
brew 'ruby-build'

# Node
brew 'node'

# Python
brew 'python'

# Applications
cask '1password'
cask 'alfred'
cask 'docker-beta'
cask 'fantastical'
cask 'firefox'
cask 'flash'
cask 'flux'
cask 'google-chrome'
cask 'iterm2-beta'
cask 'java7'
cask 'keepingyouawake'
cask 'paw'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-json'
cask 'skype'
cask 'slack-beta'
cask 'spectacle'
cask 'spotify'
cask 'sublime-text-dev'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'

# Fonts
cask 'font-liberation-mono-for-powerline'
cask 'font-meslo-lg-for-powerline'
