#!/usr/bin/env zsh

# Install and update gems
gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    echo "Updating $1..."
    gem update "$@"
  else
    echo "Installing $1..."
    gem install "$@"
    rbenv rehash
  fi
}

# Fetch the latest ruby version
RUBY_VERSION="2.3.1"

# Start rbenv
eval "$(rbenv init - zsh)"

# Install the latest version of ruby
if ! rbenv versions | grep -Fq "$RUBY_VERSION"; then
  rbenv install -s "$RUBY_VERSION"
fi

rbenv global "$RUBY_VERSION"

# Install and configure bundler
gem_install_or_update 'bundler'

NUMBER_OF_CORES=$(sysctl -n hw.ncpu)
bundle config --global jobs $((NUMBER_OF_CORES - 1))

# Install gems from the Gemfile
bundle install
rbenv rehash
