#!/usr/bin/env zsh

# Install and launch a service
brew_launchctl_restart() {
  local name=$(brew info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}')
  local domain="homebrew.mxcl.$name"
  local plist="$domain.plist"

  echo "Restarting $1..."
  mkdir -p "$HOME/Library/LaunchAgents"
  ln -sfv "/usr/local/opt/$name/$plist" "$HOME/Library/LaunchAgents"

  if launchctl list | grep -Fq "$domain"; then
    launchctl unload "$HOME/Library/LaunchAgents/$plist" >/dev/null
  fi
  launchctl load "$HOME/Library/LaunchAgents/$plist" >/dev/null
}

# Start services
brew_launchctl_restart 'postgresql'
brew_launchctl_restart 'redis'
