#!/usr/bin/env zsh

# Install macvim
brew install macvim --with-cscope --with-lua --with-override-system-vim

# Create a swap directory
mkdir -p ~/.vim/backup

# Install vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install plugins
vim +PlugInstall +qall
